{"name": "test_broken", "status": "broken", "statusDetails": {"message": "Exception: oops", "trace": "self = <testcase.test_login.Testfour object at 0x7f7dc26b3640>\n\n    def test_broken(self):\n>       raise Exception('oops')\nE       Exception: oops\n\ntest_login.py:118: Exception"}, "start": 1652844302500, "stop": 1652844302500, "uuid": "74c03d70-10f3-41c7-9191-060226797a59", "historyId": "30bb666e68d2c752af936ba2ac037f11", "testCaseId": "01a100b4540167d6026ec96a476def21", "fullName": "testcase.test_login.Testfour#test_broken", "labels": [{"name": "feature", "value": "测试报告显示"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Testfour"}, {"name": "host", "value": "tangzhongkaideMacBook-Pro.local"}, {"name": "thread", "value": "49233-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_login"}]}