{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <testcase.test_login.Testfour object at 0x7f7dc26b33a0>\n\n    def test_failure(self):\n>       assert False\nE       assert False\n\ntest_login.py:112: AssertionError"}, "start": 1652844302492, "stop": 1652844302492, "uuid": "e83af7e6-81b6-4d0d-bf95-5b6fc44c0ec1", "historyId": "1da189b98a479a1598281b3e24b00460", "testCaseId": "cfcc5c682e6009ed71ae1b7ccdd8d9c4", "fullName": "testcase.test_login.Testfour#test_failure", "labels": [{"name": "feature", "value": "测试报告显示"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Testfour"}, {"name": "host", "value": "tangzhongkaideMacBook-Pro.local"}, {"name": "thread", "value": "49233-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_login"}]}