{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <testcase.test_login.Testfour object at 0x7f9436f468f0>\n\n    @allure.story(\"失败模块\")\n    def test_failure(self):\n>       assert False\nE       assert False\n\ntestcase/test_login.py:116: AssertionError"}, "start": 1652845175415, "stop": 1652845175415, "uuid": "09c98bba-0191-428b-8708-07a7ba5bbb6d", "historyId": "1da189b98a479a1598281b3e24b00460", "testCaseId": "cfcc5c682e6009ed71ae1b7ccdd8d9c4", "fullName": "testcase.test_login.Testfour#test_failure", "labels": [{"name": "feature", "value": "测试报告显示"}, {"name": "story", "value": "失败模块"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Testfour"}, {"name": "host", "value": "tangzhongkaideMacBook-Pro.local"}, {"name": "thread", "value": "56048-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_login"}]}